name: Generate pot file

on:
  workflow_dispatch:

jobs:
  release:
    name: Generate pot file
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2

      -   name: Generate pot file
          run: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            mv wp-cli.phar /usr/local/bin/wp
            wp i18n make-pot . languages/plugin.pot

      -   name: Verify pot file
          run: |
            ls languages